### ISSUE TITLE
[BUG]:Issue while using Ansible loop for mapping  of Unity LUNs to multiple Host

### ISSUE THREAD

**Issue by vinugupta80** [dell/ansible-unity#15]
I am facing issue while using Ansible loop for mapping  of Unity LUNs to multiple Host.

Attached the file having 3 scenarios.

In scenario 3 :  I am using a Static value for Host_name and HLU inside Hosts: in playbook and everything is working fine.
But issue is if we have more hosts in place we have to modify the playbook every time.
![image](https://user-images.githubusercontent.com/61389511/163992036-90a7ed3c-1f97-481c-8fde-5acd63205097.png)

In Scenario 1 : Using Loop and Host_name & HLU inside Hosts: In this case my play failed with error msg: "Invalid input parameter for host_name"
![image](https://user-images.githubusercontent.com/61389511/163992093-6337c464-e1b7-4247-9f4b-3e2b0d243716.png)
In Scenario 2: Task Run Successfully but LUN allocated to One Host , not respecting Idempotent feature. Task Run twice and when it run 2nd time it removes the host added during Task 1
![image](https://user-images.githubusercontent.com/61389511/163992123-1b70d316-efa6-4cf2-b128-df3ab79b10a1.png)

**System Information (please complete the following information):**
 - OS/Version: [e.g. RHEL 7.6]
 - Ansible Version [e.g. 2.12]
 - Python Version [e.g. 3.9]  
 - Additional Information...

**Additional context**
[Ansible_loop.xlsx](https://github.com/dell/ansible-unity/files/8512458/Ansible_loop.xlsx)

[Ansible_loop.xlsx](https://github.com/dell/ansible-unity/files/8512461/Ansible_loop.xlsx)

**Comment by anupamaloke** [comment]
Closed by #19
