### ISSUE TITLE
[FEATURE]: Failover and Failback

### ISSUE THREAD

**Issue by cristianmusat** [dell/ansible-unity#20]
**Describe the solution you'd like**
What about Failover and Failback module for replicated NFS Servers ? It is a feture urgent needed.

**Describe alternatives you've considered**
From Web Client this scenario is possible. 

**Additional context**
We have worked on a huge ansible project to automate switch from one principal site to a secondary site. We have all we need to manage networks , vm's, databases but at storage level we can not because this option is missing.

**Comment by paulehr** [comment]
I would like to see this as well, currently I am relying on anisble running the uemcli command on the control server to failover/failback sessions between our unity's. it works but it's a little kludgy.

**Comment by anupamaloke** [comment]
Closed by #38
