### ISSUE TITLE
Add new module to start sync of configured manual replication

### ISSUE THREAD

**Issue by Varun-Sharawat** [dell/ansible-unity#32]
Please add new module specific to replication task. As of now there is only "Consistency Group" module which can create or delete the replication however there is no module for below purpose.

1.  Pause
2.  Resume
3. Failover
4. Failover with Sync
5. Sync
6. Failback

Consistency Group --> View/Edit --> Replication

**Comment by anupamaloke** [comment]
@Varun-Sharawat, thank you for submitting the feature request. Just so you know this is in our backlog of feature requests and we will be accordingly planning to deliver for our upcoming releases.
